inherit_gem:
  folio: lib/rubocop_config.yml

Lint/UselessAssignment:
  Exclude:
    - test/jobs/boutique/orders/deliver_gifts_job_test.rb
    - test/lib/boutique/mailer_bot_test.rb
    - test/lib/boutique/subscription_bot_test.rb
    - test/models/boutique/subscripion_test.rb

