linters:
  RuboCop:
    enabled: false

  LineLength:
    exclude:
      - app/cells/boutique/orders/edit/show.slim
      - app/cells/boutique/orders/edit/recurrency_fields/show.slim
      - app/cells/boutique/orders/edit/subscription_fields/show.slim
      - app/cells/boutique/subscriptions/recurrent_payment_label/show.slim
      - app/cells/boutique/ui/gift_icon/show.slim
      - app/cells/folio/console/boutique/orders/catalogue/show.slim
      - app/cells/folio/console/boutique/subscriptions/catalogue/show.slim
      - app/views/folio/console/boutique/orders/index.slim
