linters:
  RuboCop:
    enabled: false

  LineLength:
    exclude:
      - app/cells/boutique/orders/cart/show.slim
      - app/cells/boutique/orders/cart/recurrency_fields/show.slim
      - app/cells/boutique/subscriptions/recurrent_payment_label/show.slim
      - app/cells/boutique/ui/gift_icon/show.slim
      - app/views/folio/console/boutique/orders/index.slim
      - app/cells/folio/console/boutique/orders/catalogue/show.slim
      - app/views/folio/console/boutique/subscriptions/_form.slim
      - app/cells/folio/console/boutique/subscriptions/catalogue/show.slim
      - test/dummy/app/views/home/index.slim
